#!/bin/sh

export MONO_OPTIONS="--debug"
export MONO_LOG_LEVEL=debug

fastcgi-mono-server4 /applications=/$VIRTUAL_SUBDIRECTORY:/$VIRTUAL_SUBDIRECTORY /socket=tcp:$(ip -4 addr show eth2 | grep -Po 'inet \K[\d.]+'):9000 /verbose=True /printlog=True
