#!/bin/sh

# export environment variables
export MONO_OPTIONS="--debug"
export MONO_LOG_LEVEL=debug

# start the mono-fastcgi-server4
fastcgi-mono-server4 /applications=/$VIRTUAL_SUBDIRECTORY/:/$VIRTUAL_SUBDIRECTORY/ /socket=tcp:$(cat /etc/hosts | grep $(cat /etc/hostname) | awk '{print $1;}'):9000 /verbose=True /printlog=True
