version: '3.1'
 
services:

  jenkins-master:
    image: jenkins-master:dev
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JENKINS_OPTS=--prefix=/gpr1/jenkins
      - NGINX_PROXY_SUBDIRECTORY=gpr1/jenkins
      - VIRTUAL_PORT=8080
    secrets:
      - jenkins-user
      - jenkins-pass
      - jenkins-node-private-key
    networks:
      - jenkins-network
    depends_on:
      - "gitblit"

  jenkins-job-builder:
    image: jenkins-job-builder:dev
    environment:
      - FACH_FULL=gpr1/jenkins
    networks:
      - jenkins-network
    depends_on:
      - "gitblit"

  jenkins-slave:
    image: jenkins-slave:dev
    ports:
      - 22:22
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDoQrMrv2h1fw1GJ4Hwa/Rat7Us1fJB8zzdH28rdihuN9qwfGGpdytqMtjmVNkFBtiDiC8NmQ2+qpk8y05Uy6dxrpgoHDHNwHpVuwux9F3XZ2VUsBunovIhHJwDu8sdHJAWu0mPVsSrCXHuKH6TvjNzpZhzYKiNFi7Eo6PfdVOgBgggErCSw6CxU37oa/JjGj93BnzbIoX4zbTFM8qsiISkRsR5/xXPsM4hPqCKs+iViUvGZ8ymnWVznegJrDYScwEnuHTE8AM3d20pfoPoTyyegQi8JRIC19SFfm18CRjWG+HG/S2QPgrs+3j/BhIEkk8YVUTwsRsM0aWQh66ewDj
    networks:
      - jenkins-network
    depends_on:
      - "gitblit"
  
  gitblit:
    image: gitblit:dev
    ports:
      - 8181:8080
      - 8443:8443
      - 9418:9418
      - 29418:29418
    environment:
      - NGINX_PROXY_SUBDIRECTORY=gpr1/git
      - VIRTUAL_PORT=8080
    networks:
      - jenkins-network

  database:
    image: database:dev
    environment: 
      - POSTGRES_DB=Abgabe
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  adminer:
    image: adminer
    ports:
      - 8585:8080

  application:
    image: application:dev
    environment:
      - NGINX_PROXY_SUBDIRECTORY=gpr1/Assignment
      - VIRTUAL_PROTO=fastcgi
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 9000:9000
    networks:
      - jenkins-network
    depends_on:
      - "database"
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
  jenkins-node-private-key:
    external: true
  jenkins-node-public-key:
    external: true

networks:
  jenkins-network:
     driver: overlay

