version: '3.1'
 
services:

  jenkins-master:
    image: jenkins-master:dev
#    ports:
#      - 8080
    environment:
      - INTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/gpr1-internal-git-private-key
      - SSH_SLAVE_PRIVATE_KEY_FILE=/run/secrets/gpr1-ssh-slave-private-key
      - INTERNAL_GIT_USER_FILE=/run/secrets/gpr1-internal-git-user
      - JENKINS_USER_FILE=/run/secrets/gpr1-jenkins-user
      - JENKINS_PASSWORD_FILE=/run/secrets/gpr1-jenkins-password
      - JENKINS_OPTS=--prefix=/gpr1/jenkins
      - NGINX_PROXY_SUBDIRECTORY=gpr1/jenkins
      - VIRTUAL_PORT=8080
    secrets:
      - internal-git-private-key
      - ssh-slave-private-key
      - internal-git-user
      - jenkins-user
      - jenkins-password
    networks:
      - course-network
    volumes:
      - jenkins-master-home-data:/var/jenkins_home
    depends_on:
      - "gitblit"

  jenkins-job-builder:
    image: jenkins-job-builder:dev
    environment:
      - EXTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/gpr1-external-git-private-key
      - INTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/gpr1-internal-git-private-key
      - SSH_SLAVE_PUBLIC_KEY_FILE=/run/secrets/gpr1-ssh-slave-public-key
      - INTERNAL_GIT_USER_FILE=/run/secrets/gpr1-internal-git-user
      - JENKINS_USER_FILE=/run/secrets/gpr1-jenkins-user
      - JENKINS_PASSWORD_FILE=/run/secrets/gpr1-jenkins-password
      - COURSE=BIF-WS18-GPR1
      - JENKINS_SUBDIRECTORY=gpr1/jenkins
    secrets:
      - external-git-private-key
      - internal-git-private-key
      - ssh-slave-public-key
      - internal-git-user
      - jenkins-user
      - jenkins-password
    networks:
      - course-network
    depends_on:
      - "gitblit"

  jenkins-slave:
    image: jenkins-slave-build-essential:dev
    environment:
      - EXTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/gpr1-external-git-private-key
      - INTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/gpr1-internal-git-private-key
      - SSH_SLAVE_PUBLIC_KEY_FILE=/run/secrets/gpr1-ssh-slave-public-key
      - INTERNAL_GIT_USER_FILE=/run/secrets/gpr1-internal-git-user
      - POSTGRES_USER_FILE=/run/secrets/gpr1-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/gpr1-postgres-password
    secrets:
      - external-git-private-key
      - internal-git-private-key
      - ssh-slave-public-key
      - internal-git-user
      - postgres-user
      - postgres-password
    networks:
      - course-network
    volumes:
      - jenkins-slave-home-data:/home/jenkins
      - jenkins-slave-workspace-custom-data:/workspace-custom
    depends_on:
      - "gitblit"
  
  gitblit:
    image: gitblit:dev
#    ports:
#      - 8080
    environment:
      - INTERNAL_GIT_PUBLIC_KEY_FILE=/run/secrets/gpr1-internal-git-public-key
      - INTERNAL_GIT_USER_FILE=/run/secrets/gpr1-internal-git-user
      - INTERNAL_GIT_PASSWORD_FILE=/run/secrets/gpr1-internal-git-password
      - JENKINS_SUBDIRECTORY=gpr1/jenkins
      - NGINX_PROXY_SUBDIRECTORY=gpr1/gitblit
      - VIRTUAL_PORT=8080
    secrets:
      - internal-git-public-key
      - internal-git-user
      - internal-git-password
    networks:
      - course-network
    volumes:
      - gitblit-repository-data:/opt/gitblit-data/gitblit-repositories

  database:
    image: database:dev
    environment: 
      - POSTGRES_USER_FILE=/run/secrets/gpr1-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/gpr1-postgres-password
      - POSTGRES_DB=Abgabe
    secrets:
      - postgres-password
      - postgres-user
    networks:
      - course-network
    volumes:
      - database-data:/var/lib/postgresql/data

  application:
    image: application:dev
    environment:
      - POSTGRES_USER_FILE=/run/secrets/gpr1-postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/gpr1-postgres-password
      - NGINX_PROXY_SUBDIRECTORY=gpr1/assignment
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_SUBDIRECTORY=gpr1-assignment
#    ports:
#      - 9000
    secrets:
      - postgres-user
      - postgres-password
    networks:
      - course-network
    volumes:
      - gitblit-repository-data:/gitblit-repositories
    depends_on:
      - "database"
 
secrets:
  gpr1-external-git-private-key:
    external: true
  gpr1-internal-git-private-key:
    external: true
  gpr1-internal-git-public-key:
    external: true
  gpr1-ssh-slave-private-key:
    external: true
  gpr1-ssh-slave-public-key:
    external: true
  gpr1-internal-git-user:
    external: true
  gpr1-internal-git-password:
    external: true
  gpr1-postgres-user:
    external: true
  gpr1-postgres-password:
    external: true
  gpr1-jenkins-user:
    external: true
  gpr1-jenkins-password:
    external: true

networks:
  course-network:
     driver: overlay

volumes:
  jenkins-master-home-data:
    driver: local
  jenkins-slave-home-data:
    driver: local
  jenkins-slave-workspace-custom-data:
    driver: local
  gitblit-repository-data:
    driver: local
  database-data:
    driver: local

