version: '3.1'
 
services:

  jenkins-master:
    image: jenkins-master:dev
#    ports:
#      - 8080
    environment:
      - INTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/internal-git-private-key
      - SSH_SLAVE_PRIVATE_KEY_FILE=/run/secrets/ssh-slave-private-key
      - JENKINS_OPTS=--prefix=/gpr1/jenkins
      - NGINX_PROXY_SUBDIRECTORY=gpr1/jenkins
      - VIRTUAL_PORT=8080
      - JENKINS_USER_FILE=/run/secrets/jenkins-user
      - JENKINS_PASSWORD_FILE=/run/secrets/jenkins-password
    secrets:
      - internal-git-private-key
      - ssh-slave-private-key
      - jenkins-user
      - jenkins-password
    networks:
      - course-network
    depends_on:
      - "gitblit"

  jenkins-job-builder:
    image: jenkins-job-builder:dev
    environment:
      - INTERNAL_GIT_USER_FILE=/run/secrets/internal-git-user
      - INTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/internal-git-private-key
      - EXTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/external-git-private-key
      - SSH_SLAVE_PUBLIC_KEY_FILE=/run/secrets/ssh-slave-public-key
      - JENKINS_USER_FILE=/run/secrets/jenkins-user
      - JENKINS_PASSWORD_FILE=/run/secrets/jenkins-password
      - COURSE=BIF-WS18-GPR1
      - JENKINS_SUBDIRECTORY=gpr1/jenkins
    secrets:
      - internal-git-user
      - internal-git-private-key
      - external-git-private-key
      - ssh-slave-public-key
      - jenkins-user
      - jenkins-password
    networks:
      - course-network
    depends_on:
      - "gitblit"

  jenkins-slave:
    image: jenkins-slave:dev
    environment:
      - INTERNAL_GIT_USER_FILE=/run/secrets/internal-git-user
      - POSTGRES_USER_FILE=/run/secrets/postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - INTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/internal-git-private-key
      - EXTERNAL_GIT_PRIVATE_KEY_FILE=/run/secrets/external-git-private-key
      - SSH_SLAVE_PUBLIC_KEY_FILE=/run/secrets/ssh-slave-public-key
      - JENKINS_SLAVE_SSH_PUBKEY=
    secrets:
      - internal-git-user
      - postgres-user
      - postgres-password
      - internal-git-private-key
      - external-git-private-key
      - ssh-slave-public-key
    networks:
      - course-network
    depends_on:
      - "gitblit"
  
  gitblit:
    image: gitblit:dev
#    ports:
#      - 8080
    environment:
      - NGINX_PROXY_SUBDIRECTORY=gpr1/gitblit
      - VIRTUAL_PORT=8080
      - INTERNAL_GIT_USER_FILE=/run/secrets/internal-git-user
      - INTERNAL_GIT_PASSWORD_FILE=/run/secrets/internal-git-password
      - INTERNAL_GIT_PUBLIC_KEY_FILE=/run/secrets/internal-git-public-key
      - JENKINS_SUBDIRECTORY=gpr1/jenkins
    secrets:
      - internal-git-public-key
      - internal-git-user
      - internal-git-password
    networks:
      - course-network
    volumes:
      - gitblit-repository-data:/opt/gitblit-data/gitblit-repositories

  database:
    image: database:dev
    environment: 
      - POSTGRES_DB=Abgabe
      - POSTGRES_USER_FILE=/run/secrets/postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    secrets:
      - postgres-password
      - postgres-user
    networks:
      - course-network

  application:
    image: application:dev
    environment:
      - NGINX_PROXY_SUBDIRECTORY=gpr1/assignment
      - VIRTUAL_SUBDIRECTORY=gpr1-assignment
      - VIRTUAL_PROTO=fastcgi
      - POSTGRES_USER_FILE=/run/secrets/postgres-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
#    ports:
#      - 9000
    secrets:
      - postgres-user
      - postgres-password
    networks:
      - course-network
    volumes:
      - gitblit-repository-data:/gitblit-repositories
    depends_on:
      - "database"
 
secrets:
  external-git-private-key:
    external: true
  internal-git-private-key:
    external: true
  internal-git-public-key:
    external: true
  ssh-slave-private-key:
    external: true
  ssh-slave-public-key:
    external: true
  internal-git-user:
    external: true
  internal-git-password:
    external: true
  postgres-user:
    external: true
  postgres-password:
    external: true
  jenkins-user:
    external: true
  jenkins-password:
    external: true

networks:
  course-network:
     driver: overlay

volumes:
  gitblit-repository-data:
     driver: local

