FROM postgres:latest

#COPY 01_init_CreateDB.sh /docker-entrypoint-initdb.d/01.sh
#COPY 02_init_CreateTableUnitTestResults.sh /docker-entrypoint-initdb.d//02.sh
#COPY 03_init_CreateTableCourses.sh /docker-entrypoint-initdb.d/03.sh
#COPY 04_init_CreateTableGroupWorks.sh /docker-entrypoint-initdb.d/04.sh
#COPY 05_init_CreateTableGroupWorkMembers.sh /docker-entrypoint-initdb.d/05.sh
#COPY 06_init_CreateViewRptUebungen.sh /docker-entrypoint-initdb.d/06.sh
#COPY 07_init_CreateViewRptExam.sh /docker-entrypoint-initdb.d/07.sh
#COPY 08_init_CreateProcedureStoreUnitTestResults.sh /docker-entrypoint-initdb.d/08.sh
#COPY 09_init_CreateProcedureGetVersion.sh /docker-entrypoint-initdb.d/09.sh

#WORKDIR /docker-entrypoint-initdb.d
#RUN chmod +x 01.sh
#RUN chmod +x 02.sh
#RUN chmod +x 03.sh
#RUN chmod +x 04.sh
#RUN chmod +x 05.sh
#RUN chmod +x 06.sh
#RUN chmod +x 07.sh
#RUN chmod +x 08.sh
#RUN chmod +x 09.sh
