FROM jenkins/jenkins:lts

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

USER jenkins

COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy
COPY credentials.groovy /usr/share/jenkins/ref/init.groovy.d/credentials.groovy
COPY slave.groovy /usr/share/jenkins/ref/init.groovy.d/slave.groovy
 
COPY plugins.txt /tmp/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /tmp/plugins.txt

COPY --chown=jenkins known_hosts /var/jenkins_home/.ssh/known_hosts
COPY --chown=jenkins jenkins-slave-rsa /var/jenkins_home/.ssh/gitblit.key 
COPY --chown=jenkins config /var/jenkins_home/.ssh/config

#RUN chown -R jenkins:jenkins /var/jenkins_home/.ssh
#X
RUN chmod 600 /var/jenkins_home/.ssh/gitblit.key

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
